### PR TITLE
Fix/4/link domain name

### LINKED ISSUE #4: [Domains] Link a domain name to an application

### PR DESCRIPTION
**Pull request by ichbinkour**
Fix #4

### CODE REVIEW

**Comment by Soulou** [comment]
Why is the commit `0.0.7` in the PR?

**Comment by Soulou** [comment]
I would rather stay in the standard or CRUD naming, so base operations should be named `create`, `find`, `update`, `destroy`

So please rename `link` to `create`, as it's what we're doing here, Creating a new domain

**Comment by yannski** [comment]
Indeed "link" is the "business" name of this functionnality

**Comment by yannski** [comment]
IMHO "link" can stay in the documentation though

**Comment by ichbinkour** [comment]
> Why is the commit `0.0.7` in the PR?

**Pull request closed without merging**
